module2-task1
htmlacademy-vue/976593-pizza-1 pull request #2
Opened 2022-09-04 20:51 UTC by SerenyaDyadev

2022-09-04 21:34 UTC, enotke requested changes

2022-09-04 21:34 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +      default: () => {},
Так ты объявляешь функцию

2022-09-04 21:34 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPizzaView.vue
> +<style lang="scss" scoped>
А зачем столько стилей в компонентах? Их можно подключить глобально один раз

2022-09-04 21:34 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        $emit('updateOrder', {
По хорошему конечно нужно обрабатывать клик на кнопку, а не на лейбл

2022-09-04 21:34 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <button type="button" class="button" :disabled="disabled">Готовьте!</button>
Добавление в корзину должно происходить после нажатия кнопки "Готовьте"

2022-09-04 21:34 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <button type="button" class="button" :disabled="disabled">Готовьте!</button>
Также должна очищаться форма

2022-09-05 09:42 UTC, SerenyaDyadev commented on src/frontend/src/modules/builder/components/BuilderDoughSelector.vue
> +        $emit('updateOrder', {
Кнопка "под" лейблом, как лучше обрабатывать это клик, не представляю...

2022-09-05 09:44 UTC, SerenyaDyadev commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +    <button type="button" class="button" :disabled="disabled">Готовьте!</button>
В настоящий момент этот функционал не касается именно этого модуля, но реализовать очистку по нажатию можно.

2022-09-05 23:42 UTC, enotke requested changes

2022-09-05 23:42 UTC, enotke commented on src/frontend/src/modules/builder/components/BuilderPriceCounter.vue
> +      return this.priceCounter === 0;
Нужно проверять не стоимость, а то что у пиццы есть название, тесто, размер.... А так можно добавить выбрав только ингредиент

2022-09-05 23:42 UTC, merged